# Generated by Django 5.2.15 on 2026-06-08 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.AlterField(
            model_name='areas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Nome')),
                ('resumo', models.TextField(max_length=500, verbose_name='Resumo')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('vagas', models.IntegerField(verbose_name='Vagas')),
                ('foto', models.ImageField(upload_to='media', verbose_name='Foto')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.areas')),
                ('publicos', models.ManyToManyField(to='core.publicos')),
            ],
        ),
    ]
