# Generated by Django 5.2.15 on 2026-06-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_areas_id_alter_cursos_id_alter_publicos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Foto'),
        ),
    ]
