# Generated by Django 5.2.7 on 2025-10-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Instrutor')),
            ],
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Público')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Curso')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição')),
                ('vagas', models.IntegerField(verbose_name='Vagas')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.area')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.instrutor')),
                ('publicos', models.ManyToManyField(to='banco.publico')),
            ],
        ),
    ]
